version: "3"

services:
  app:
    image: ghcr.io/khlam/docker-vscode/vscode:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host